build: off

image:
  - Ubuntu

clone_folder: /github.com/aliyun/darabonba-go-generator

stack: node 10

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

after_test:
  - bash <(curl -s https://codecov.io/bash)